import Head from "next/head";
import Nav from "../components/nav";
import Enroll from "../components/enroll";
import Hero from "../components/hero";
import Week from "../components/week";
import Testimonial from "../components/testimonial";
import StudentStar1 from "../components/svg/studentstar1";
import StudentStar2 from "../components/svg/studentstar2";
import StudentStar3 from "../components/svg/studentstar3";
import AboutDustin from "../components/svg/aboutdustin";
import Title2 from "../components/svg/title2";
import Title3 from "../components/svg/Title3";
import Title4 from "../components/svg/title4";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Magpie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Enroll />
      <main>
        <Hero />
        <section id="method" className="bg-pink px-marginDesktop py-32">
          <div className="flex flex-column justify-center">
            <Title2 />
          </div>
          <div class="foundations bg-white rounded-full pt-12 pb-8 px-24 mt-24">
            <div className="flex flex-col">
              <hgroup>
                <h3 className="text-title">流利度</h3>
                <h2 className="text-title font-bold">Fluency</h2>
              </hgroup>
              <p className="text-body">
                is the most important part of{" "}
                <span className="font-bold">speaking</span> because it helps us
                to communicate our ideas as naturally as possible.
              </p>
            </div>
            <div className="flex flex-col">
              <hgroup>
                <h3 className="text-title">置信度</h3>
                <h2 className="text-title font-bold">Self Confidence</h2>
              </hgroup>
              <p className="text-body">
                is understanding that we trust our own judgment and abilities,
                and that <span className="font-bold">we value ourselves.</span>{" "}
                Self-confidence gives us permission to be ourselves!
              </p>
            </div>
            <div className="flex flex-col">
              <hgroup>
                <h3 className="text-title">性格</h3>
                <h2 className="text-title font-bold">Creativity</h2>
              </hgroup>
              <p className="text-body">
                is the act of turning new and imaginative ideas into reality.
                Creativity is at the <span className="font-bold">heart</span> of
                Magpie English.
              </p>
            </div>
          </div>
        </section>
        <section id="program" className="bg-yellow px-marginDesktop py-32">
          <div className="flex flex-column justify-center">
            <Title3 />
          </div>
          <ol className="weeks-list w-full mt-24">
            <Week
              number="一 1"
              title="Speech Communication Process"
              description=""
              color="neonYellow"
            />
            <Week
              number="二 2"
              title="Effective Listening"
              description=""
              color="white"
            />
            <Week
              number="三 3"
              title="Preparing Speech"
              description=""
              color="neonYellow"
            />
            <Week
              number="四 4"
              title="Developing and Supporting Your Ideas"
              description=""
              color="white"
            />
            <Week
              number="五 5"
              title="Impromptu Speech"
              description=""
              color="neonYellow"
            />
            <Week
              number="六 6"
              title="Persuasive Speaking"
              description=""
              color="white"
            />
          </ol>
        </section>
        <section id="why-magpie" className="bg-green px-marginDesktop py-32">
          <div className="flex flex-column justify-center">
            <Title4 />
          </div>
          <div className="testimonials mt-16">
            <Testimonial
              svg={<StudentStar1 />}
              subtitle="流利度"
              title="Chen"
              description="“Dustin taught me it’s OK to make mistakes and it’s also OK to be a pimp!”"
            />
            <Testimonial
              svg={<StudentStar2 />}
              subtitle="置信度"
              title="David"
              description="“I am sad that Dustin is leaving because he always shares his ciggies with me”"
            />
            <Testimonial
              svg={<StudentStar3 />}
              subtitle="性格"
              title="Emily"
              description="“Dustin helped me get into Harvard and taught me hold my liquour!” "
            />
          </div>
        </section>
        <section
          id="about-dustin"
          className="bg-blueLight px-marginDesktop pt-16 pb-32"
        >
          <div className="about-dustin bg-opacity-20 p-12 bg-blueDark">
            <AboutDustin />
            <div>
              <h1 className="text-title font-bold">Dustin Chok</h1>
              <p className="text-body pr-20">
                Hi! I’m Teacher Dustin. <br />
                <br />
                My goal as an ESL teacher is more than just helping you learn a
                new language; I wish to help you discover new and interesting
                parts about yourself through language. <br />
                <br /> Fluency will help us foster self-confidence which will
                allow us to interact creatively. <br />
                <br /> My teaching method focuses on creativity because, yes,
                learning should be fun and interesting, but it can also help us
                discover the types of people we want to be.
              </p>
            </div>
          </div>
        </section>
      </main>

      <footer></footer>
    </div>
  );
}
